In [216]:
import pandas as pd
import numpy as np
from datetime import datetime

## Feature 1

In [217]:
df = pd.read_csv("Data set for DADS June.csv")

In [218]:
df.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962

In [219]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

Shape: (1328, 8)

Columns:
['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode', 'Ref']

Data types:
Date            object
Time            object
Description     object
Type            object
Amount          object
Balance        float64
Mode            object
Ref             object
dtype: object

Missing values:
Date           0
Time           0
Description    0
Type           0
Amount         0
Balance        0
Mode           0
Ref            0
dtype: int64

In [220]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1328 entries, 0 to 1327
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         1328 non-null   object
 1   Time         1328 non-null   object
 2   Description  1328 non-null   object
 3   Type         1328 non-null   object
 4   Amount       1328 non-null   object
 5   Balance      1328 non-null   float64
 6   Mode         1328 non-null   object
 7   Ref          1328 non-null   object
dtypes: float64(1), object(7)
memory usage: 83.1+ KB

In [221]:
df["Type"].value_counts()

Type
DR       670
Debit    652
CR         6
Name: count, dtype: int64

In [222]:
df["Description"].unique()

array(['AMAZON SELLER SVCS', 'BHIM-BMTC',
       'NEFT-TECHCRUSH LABS-SALARY MAY24', 'UPI-AMAN-8934@OKAXIS',
       'BHIM-BLINKIT', 'BHIM ZEPTO', 'UPI-UBER-2426@HDFCBANK',
       'POS SWIGGY BANGALORE', 'UPI-GROWWPAY@HDFCBANK', 'OLA ELECTRIC',
       'BMS MOVIE TICKETS', 'POS OLA-PRIME', 'SWIGGY-INSTAMART',
       'UPI-STARBUCKS@AXIS', 'UPI-THIRDWAVE@OKAXIS', 'ANI Technologies',
       'BMTC BUS PASS', 'POS TRUFFLES', 'FLIPKART INDIA',
       'POS SWIGGY-RESTAURANT', 'GROFERS INDIA P L', 'POS UBER BANGALORE',
       'BANGALORE ELEC SUPPLY', 'TWC INDIA', 'UPI-BESCOM-BILL@HDFCBANK',
       'UPI-AMAN-0816@OKAXIS', 'ROPPEN TRANSPORTATION', 'OLA CABS',
       'POS ZOMATO', 'UPI-AMAZONPAY@HDFCBANK', 'POS BLINKIT',
       'IMPS-RENT-LANDLORD-75500265', 'ZOMATO MEDIA P L',
       'UPI-ANKIT-6430@OKAXIS', 'UPI-OLACABS@HDFCBANK',
       'UPI-JIORECHARGE@PAYTM', 'UPI-CCD@HDFCBANK', 'Swiggy*Order',
       'INSTAMART BANGALORE', 'UPI-ZOMATO-LIMITED@PAYTM',
       'AVENUE SUPERMARTS', 'POS HP PETROL STATION',
       'UPI-VIKAS-6060@OKAXIS', 'POS BANGALORE RESTAURANT',
       'UPI-ZERODHA-COIN@AXIS', 'BHIM SWIGGY', 'UPI-BOOKMYSHOW@HDFCBANK',
       'BLINKIT BANGALORE', 'POS ZEPTO BANGALORE', 'UPI-DMART@OKAXIS',
       'UPI-RAPIDO@OKAXIS', 'BUNDL Tech P L', 'TATA STARBUCKS',
       'POS CAFE COFFEE DAY', 'UBER SYSTEMS INDIA', 'UPI-MYNTRA@HDFCBANK',
       'UPI-FLIPKART@HDFCBANK', 'UPI-BWSSB@AXIS',
       'UPI-ZOMATO6393@OKICICI', 'AMAZON IN', 'UPI-NETFLIX-MEMB@HDFCBANK',
       'AIRTEL POSTPAID', 'Amazon Pay India', 'UPI-PRIYA-2221@OKAXIS',
       'POS FLIPKART BANGALORE', 'POS NYKAA BANGALORE', 'VI POSTPAID',
       'UPI-UBER-6457@HDFCBANK', 'POS BPCL PETROL PUMP', 'TUMMOC-BMTC',
       'POS INDIAN OIL BANGALORE', 'UPI-SPOTIFY-IN@AXIS', 'POS DINEOUT',
       'UPI-BLINKIT-0656@PAYTM', 'UPI-SWIGGY5057@OKAXIS', 'ZOMATO-DINING',
       'COFFEE DAY GLOBAL', 'UPI-NYKAA@AXIS', 'UPI-SWIGGY9672@OKAXIS',
       'RAPIDO BIKE TAXI', 'UPI-SWIGGY-6560@HDFCBANK', 'DISNEY HOTSTAR',
       'NEFT ZERODHA BROKING', 'UBER INDIA', 'AMAZONIN MARKETPLACE',
       'UPI-ZOMATO4674@OKICICI', 'POS EMPIRE RESTAURANT',
       'ATM-WDL-SBI-5715', 'UPI-SWIGGY-9474@HDFCBANK',
       'POS MEGHANA FOODS', 'ZEPTO MARKETPLACE', 'UPI-IOC9075@HDFCBANK',
       'UPI-SWIGGY-2954@HDFCBANK', 'FKART INTRNET',
       'UPI-SWIGGY-5808@HDFCBANK', 'UPI-BIGBASKET@HDFCBANK',
       'AMZN-INTPYMT', 'AMZN PRIME', 'MYNTRA-ORDER',
       'UPI-SWIGGY-5551@HDFCBANK', 'BUNDL TECH-INSTAMART',
       'MYNTRA DESIGNS', 'POS MYNTRA', 'POS DMART BANGALORE',
       'BIGBASKET BANGALORE', 'POS THIRD WAVE COFFEE', 'SPOTIFY INDIA',
       'UPI-SWIGGY-7959@HDFCBANK', 'UPI-BLINKIT-3798@PAYTM',
       'UPI-BLINKIT-3397@PAYTM', 'UPI-SWIGGY-INSTAMART@OKAXIS',
       'ZOMATO BENGALURU', 'BESCOM ELEC BILL',
       'IMPS-RENT-LANDLORD-39598076', 'UPI-RESTAURANT-7285@PAYTM',
       'POS STARBUCKS BANGALORE', 'UPI-SWIGGY2461@OKAXIS',
       'UPI-SWIGGY4619@OKAXIS', 'IMPS ZERODHA-COIN',
       'UPI-SWIGGY3675@OKAXIS', 'RELIANCE JIO',
       'UPI-SWIGGY-1309@HDFCBANK', 'NETFLIX ENTERTAINMENT',
       'UPI-UBER-5667@HDFCBANK', 'FSN E-COMMERCE',
       'UPI-BLINKIT-2630@PAYTM', 'UPI-RESTAURANT-7678@PAYTM',
       'ATM-WDL-HDFC-4942', 'Uber*Trip', 'UPI-SWIGGY1616@OKAXIS',
       'UPI-NEHA-9795@OKAXIS', 'BIGTREE ENTERTAINMENT',
       'UPI-ZOMATO4177@OKICICI', 'INNOVATIVE RETAIL', 'POS INSTAMART',
       'UPI-RESTAURANT-3715@PAYTM', 'UPI-UBER-1232@HDFCBANK',
       'STAR INDIA PVT LTD', 'UPI-SWIGGY-5933@HDFCBANK',
       'UPI-RESTAURANT-0251@PAYTM', 'UPI-ZOMATO3977@OKICICI',
       'UPI-BLINKIT-7138@PAYTM', 'UPI-SWIGGY8086@OKAXIS',
       'UPI-SWIGGY-6605@HDFCBANK', 'AMAZON PRIME VIDEO',
       'UPI-SWIGGY-7844@HDFCBANK', 'UPI-SWIGGY-1487@HDFCBANK',
       'UPI-UBER-6248@HDFCBANK', 'UPI-NEHA-5906@OKAXIS',
       'KIRANAKART TECH', 'UPI-SWIGGY-7642@HDFCBANK',
       'UPI-ZEPTO-4547@HDFCBANK', 'UPI-ZEPTO-4563@HDFCBANK',
       'IMPS-RENT-LANDLORD-51148088', 'UPI-RESTAURANT-6377@PAYTM',
       'UPI-ZEPTO-3309@HDFCBANK', 'UPI-ZEPTO-0070@HDFCBANK',
       'UPI-SWIGGY-8169@HDFCBANK', 'UPI-VIKAS-5416@OKAXIS',
       'UPI-HOTSTAR@AXIS', 'ATM-WDL-HDFC-9140', 'UPI-ZOMATO6436@OKICICI',
       'ATM-WDL-SBI-4080', 'NETFLIX.COM', 'UPI-IOC0494@HDFCBANK',
       'UPI-RESTAURANT-4630@PAYTM', 'UPI-IOC1246@HDFCBANK',
       'Flipkart Internet', 'UPI-SWIGGY1600@OKAXIS',
       'UPI-SWIGGY8576@OKAXIS', 'ATM-WDL-HDFC-8030', 'SPOTIFY*PREMIUM',
       'UPI-BLINKIT-6907@PAYTM', 'BWSSB WATER BILL',
       'UPI-RESTAURANT-7888@PAYTM', 'GROWW INVEST TECH',
       'UPI-IOC2000@HDFCBANK', 'UPI-SWIGGY5466@OKAXIS',
       'UPI-SNEHA-0942@OKAXIS', 'UPI-SWIGGY-2664@HDFCBANK', 'JIOFIBER',
       'BHARTI AIRTEL LTD', 'UPI-UBER-0377@HDFCBANK',
       'UPI-UBER-5112@HDFCBANK', 'UPI-ZOMATO1274@OKICICI',
       'UPI-SWIGGY4144@OKAXIS', 'UPI-VI-RECHARGE@HDFCBANK',
       'UPI-KARAN-5789@OKAXIS', 'UPI-BLINKIT-1501@PAYTM',
       'ZERODHA-MF SIP', 'UPI-SWIGGY-9575@HDFCBANK',
       'UPI-RESTAURANT-0753@PAYTM', 'NEXTBILLION-GROWW',
       'UPI-ZOMATO5010@OKICICI', 'UPI-BLINKIT-1469@PAYTM',
       'UPI-SWIGGY9328@OKAXIS', 'NYKAA E-RETAIL', 'ATM-WDL-HDFC-3609',
       'UPI-SWIGGY0226@OKAXIS', 'UPI-SWIGGY9600@OKAXIS',
       'IMPS-RENT-LANDLORD-36852906', 'UPI-ZOMATO7344@OKICICI',
       'UPI-ZEPTO-9191@HDFCBANK', 'UPI-ZOMATO9481@OKICICI',
       'UPI-IOC2115@HDFCBANK', 'UPI-SWIGGY-3513@HDFCBANK',
       'UPI-RESTAURANT-3549@PAYTM', 'UPI-PRIYA-8750@OKAXIS',
       'UPI-ZOMATO5845@OKICICI', 'UPI-ZEPTO-6004@HDFCBANK',
       'UPI-BLINKIT-3223@PAYTM', 'UPI-SWIGGY1998@OKAXIS',
       'ATM-WDL-ICICI-6478', 'UPI-SWIGGY0250@OKAXIS',
       'UPI-RESTAURANT-5630@PAYTM', 'UPI-SWIGGY0894@OKAXIS',
       'UPI-ANKIT-9877@OKAXIS', 'UPI-SWIGGY6412@OKAXIS',
       'UPI-SWIGGY-1791@HDFCBANK', 'UPI-SWIGGY5867@OKAXIS',
       'UPI-UBER-8525@HDFCBANK', 'UPI-SWIGGY-4758@HDFCBANK',
       'UPI-BLINKIT-1165@PAYTM', 'UPI-SWIGGY4389@OKAXIS',
       'ATM-WDL-SBI-0237', 'IMPS-RENT-LANDLORD-49966195',
       'UPI-SWIGGY8720@OKAXIS', 'UPI-PRIYA-0104@OKAXIS',
       'UPI-RESTAURANT-8932@PAYTM', 'UPI-SWIGGY9756@OKAXIS',
       'UPI-SWIGGY-1714@HDFCBANK', 'VODAFONE IDEA LTD',
       'ATM-WDL-SBI-0279', 'UPI-SWIGGY-6024@HDFCBANK',
       'UPI-ZEPTO-2913@HDFCBANK', 'UPI-ZOMATO5406@OKICICI',
       'UPI-RESTAURANT-3964@PAYTM', 'UPI-SWIGGY5737@OKAXIS',
       'ATM-WDL-HDFC-8253', 'ZERODHA SECURITIES',
       'UPI-AMAZON-PRIME@HDFCBANK', 'UPI-UBER-4781@HDFCBANK',
       'UPI-RESTAURANT-5691@PAYTM', 'UPI-SWIGGY2847@OKAXIS',
       'UPI-ZOMATO9682@OKICICI', 'UPI-IOC5182@HDFCBANK',
       'UPI-ANKIT-5946@OKAXIS', 'UPI-SWIGGY9088@OKAXIS',
       'UPI-UBER-1392@HDFCBANK', 'UPI-SWIGGY9983@OKAXIS',
       'UPI-ZEPTO-1050@HDFCBANK', 'UPI-ANKIT-1837@OKAXIS',
       'IMPS-RENT-LANDLORD-35126704', 'UPI-SWIGGY8392@OKAXIS',
       'UPI-ZOMATO5117@OKICICI', 'UPI-ZOMATO4622@OKICICI',
       'UPI-SWIGGY1418@OKAXIS', 'ATM-WDL-ICICI-9135',
       'UPI-RESTAURANT-5531@PAYTM', 'UPI-ANKIT-6092@OKAXIS',
       'UPI-SWIGGY7538@OKAXIS', 'ATM-WDL-ICICI-4172',
       'UPI-ZEPTO-5207@HDFCBANK', 'ATM-WDL-SBI-4084',
       'UPI-ZEPTO-7106@HDFCBANK', 'ATM-WDL-ICICI-4739',
       'UPI-SWIGGY6053@OKAXIS', 'UPI-SWIGGY-3505@HDFCBANK',
       'UPI-SWIGGY-0015@HDFCBANK', 'UPI-RESTAURANT-2648@PAYTM',
       'ATM-WDL-SBI-0874', 'UPI-VIKAS-1878@OKAXIS',
       'UPI-SWIGGY6013@OKAXIS', 'UPI-SWIGGY-8838@HDFCBANK',
       'UPI-VIKAS-9964@OKAXIS', 'UPI-RESTAURANT-7645@PAYTM',
       'ATM-WDL-ICICI-3918', 'UPI-SWIGGY-9077@HDFCBANK',
       'UPI-RESTAURANT-0874@PAYTM', 'ATM-WDL-ICICI-5025',
       'UPI-SWIGGY3466@OKAXIS', 'UPI-BLINKIT-1828@PAYTM',
       'UPI-UBER-3218@HDFCBANK'], dtype=object)

In [223]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 18

In [224]:
df = df.drop_duplicates()

In [225]:
print(df.shape)

(1310, 8)

In [226]:
df["date"] = pd.to_datetime(
    df["Date"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

In [227]:
print("Missing dates:", df["date"].isna().sum())

Missing dates: 0

In [228]:
print(df["date"].head())
print("\nUnparseable dates:", df["date"].isna().sum())

0   2024-01-01
1   2024-01-01
2   2024-01-01
3   2024-01-01
4   2024-01-01
Name: date, dtype: datetime64[ns]

Unparseable dates: 0

In [229]:
df["amount"] = (
    df["Amount"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace("Rs.", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df["amount"] = pd.to_numeric(
    df["amount"],
    errors="coerce"
)

In [230]:
print(df[["Amount", "amount"]].head(10))
print("\nUnparseable amounts:", df["amount"].isna().sum())

    Amount   amount
0    ₹2462   2462.0
1    50.00     50.0
2   ₹84728  84728.0
3    ₹1828   1828.0
4   270.00    270.0
5  Rs. 625    625.0
6  Rs. 148    148.0
7     ₹482    482.0
8  Rs. 537    537.0
9     3956   3956.0

Unparseable amounts: 0

In [231]:
df["type_clean"] = df["Type"].astype(str).str.lower()

df["type_clean"] = df["type_clean"].replace({
    "dr": "debit",
    "debit": "debit",
    "cr": "credit",
    "credit": "credit"
})

In [232]:
print(df["type_clean"].value_counts())

type_clean
debit     1304
credit       6
Name: count, dtype: int64

In [233]:
before = len(df)

df = df.drop_duplicates().copy()

after = len(df)

print("Rows before removing duplicates:", before)
print("Rows after removing duplicates:", after)
print("Duplicates removed:", before - after)

Rows before removing duplicates: 1310
Rows after removing duplicates: 1310
Duplicates removed: 0

In [234]:
print(df.shape)
print(df.dtypes)

(1310, 11)
Date                   object
Time                   object
Description            object
Type                   object
Amount                 object
Balance               float64
Mode                   object
Ref                    object
date           datetime64[ns]
amount                float64
type_clean             object
dtype: object

In [235]:
print(df.shape)
print(df.dtypes)
print(df["type_clean"].value_counts())
print(df["date"].isna().sum())
print(df["amount"].isna().sum())

(1310, 11)
Date                   object
Time                   object
Description            object
Type                   object
Amount                 object
Balance               float64
Mode                   object
Ref                    object
date           datetime64[ns]
amount                float64
type_clean             object
dtype: object
type_clean
debit     1304
credit       6
Name: count, dtype: int64
0
0

In [236]:
print("Number of unique descriptions:", df["Description"].nunique())

print("\nAll unique descriptions:")
for description in df["Description"].unique():
    print(description)

Number of unique descriptions: 283

All unique descriptions:
AMAZON SELLER SVCS
BHIM-BMTC
NEFT-TECHCRUSH LABS-SALARY MAY24
UPI-AMAN-8934@OKAXIS
BHIM-BLINKIT
BHIM ZEPTO
UPI-UBER-2426@HDFCBANK
POS SWIGGY BANGALORE
UPI-GROWWPAY@HDFCBANK
OLA ELECTRIC
BMS MOVIE TICKETS
POS OLA-PRIME
SWIGGY-INSTAMART
UPI-STARBUCKS@AXIS
UPI-THIRDWAVE@OKAXIS
ANI Technologies
BMTC BUS PASS
POS TRUFFLES
FLIPKART INDIA
POS SWIGGY-RESTAURANT
GROFERS INDIA P L
POS UBER BANGALORE
BANGALORE ELEC SUPPLY
TWC INDIA
UPI-BESCOM-BILL@HDFCBANK
UPI-AMAN-0816@OKAXIS
ROPPEN TRANSPORTATION
OLA CABS
POS ZOMATO
UPI-AMAZONPAY@HDFCBANK
POS BLINKIT
IMPS-RENT-LANDLORD-75500265
ZOMATO MEDIA P L
UPI-ANKIT-6430@OKAXIS
UPI-OLACABS@HDFCBANK
UPI-JIORECHARGE@PAYTM
UPI-CCD@HDFCBANK
Swiggy*Order
INSTAMART BANGALORE
UPI-ZOMATO-LIMITED@PAYTM
AVENUE SUPERMARTS
POS HP PETROL STATION
UPI-VIKAS-6060@OKAXIS
POS BANGALORE RESTAURANT
UPI-ZERODHA-COIN@AXIS
BHIM SWIGGY
UPI-BOOKMYSHOW@HDFCBANK
BLINKIT BANGALORE
POS ZEPTO BANGALORE
UPI-DMART@OKAXIS
UPI-RAPIDO@OKAXIS
BUNDL Tech P L
TATA STARBUCKS
POS CAFE COFFEE DAY
UBER SYSTEMS INDIA
UPI-MYNTRA@HDFCBANK
UPI-FLIPKART@HDFCBANK
UPI-BWSSB@AXIS
UPI-ZOMATO6393@OKICICI
AMAZON IN
UPI-NETFLIX-MEMB@HDFCBANK
AIRTEL POSTPAID
Amazon Pay India
UPI-PRIYA-2221@OKAXIS
POS FLIPKART BANGALORE
POS NYKAA BANGALORE
VI POSTPAID
UPI-UBER-6457@HDFCBANK
POS BPCL PETROL PUMP
TUMMOC-BMTC
POS INDIAN OIL BANGALORE
UPI-SPOTIFY-IN@AXIS
POS DINEOUT
UPI-BLINKIT-0656@PAYTM
UPI-SWIGGY5057@OKAXIS
ZOMATO-DINING
COFFEE DAY GLOBAL
UPI-NYKAA@AXIS
UPI-SWIGGY9672@OKAXIS
RAPIDO BIKE TAXI
UPI-SWIGGY-6560@HDFCBANK
DISNEY HOTSTAR
NEFT ZERODHA BROKING
UBER INDIA
AMAZONIN MARKETPLACE
UPI-ZOMATO4674@OKICICI
POS EMPIRE RESTAURANT
ATM-WDL-SBI-5715
UPI-SWIGGY-9474@HDFCBANK
POS MEGHANA FOODS
ZEPTO MARKETPLACE
UPI-IOC9075@HDFCBANK
UPI-SWIGGY-2954@HDFCBANK
FKART INTRNET
UPI-SWIGGY-5808@HDFCBANK
UPI-BIGBASKET@HDFCBANK
AMZN-INTPYMT
AMZN PRIME
MYNTRA-ORDER
UPI-SWIGGY-5551@HDFCBANK
BUNDL TECH-INSTAMART
MYNTRA DESIGNS
POS MYNTRA
POS DMART BANGALORE
BIGBASKET BANGALORE
POS THIRD WAVE COFFEE
SPOTIFY INDIA
UPI-SWIGGY-7959@HDFCBANK
UPI-BLINKIT-3798@PAYTM
UPI-BLINKIT-3397@PAYTM
UPI-SWIGGY-INSTAMART@OKAXIS
ZOMATO BENGALURU
BESCOM ELEC BILL
IMPS-RENT-LANDLORD-39598076
UPI-RESTAURANT-7285@PAYTM
POS STARBUCKS BANGALORE
UPI-SWIGGY2461@OKAXIS
UPI-SWIGGY4619@OKAXIS
IMPS ZERODHA-COIN
UPI-SWIGGY3675@OKAXIS
RELIANCE JIO
UPI-SWIGGY-1309@HDFCBANK
NETFLIX ENTERTAINMENT
UPI-UBER-5667@HDFCBANK
FSN E-COMMERCE
UPI-BLINKIT-2630@PAYTM
UPI-RESTAURANT-7678@PAYTM
ATM-WDL-HDFC-4942
Uber*Trip
UPI-SWIGGY1616@OKAXIS
UPI-NEHA-9795@OKAXIS
BIGTREE ENTERTAINMENT
UPI-ZOMATO4177@OKICICI
INNOVATIVE RETAIL
POS INSTAMART
UPI-RESTAURANT-3715@PAYTM
UPI-UBER-1232@HDFCBANK
STAR INDIA PVT LTD
UPI-SWIGGY-5933@HDFCBANK
UPI-RESTAURANT-0251@PAYTM
UPI-ZOMATO3977@OKICICI
UPI-BLINKIT-7138@PAYTM
UPI-SWIGGY8086@OKAXIS
UPI-SWIGGY-6605@HDFCBANK
AMAZON PRIME VIDEO
UPI-SWIGGY-7844@HDFCBANK
UPI-SWIGGY-1487@HDFCBANK
UPI-UBER-6248@HDFCBANK
UPI-NEHA-5906@OKAXIS
KIRANAKART TECH
UPI-SWIGGY-7642@HDFCBANK
UPI-ZEPTO-4547@HDFCBANK
UPI-ZEPTO-4563@HDFCBANK
IMPS-RENT-LANDLORD-51148088
UPI-RESTAURANT-6377@PAYTM
UPI-ZEPTO-3309@HDFCBANK
UPI-ZEPTO-0070@HDFCBANK
UPI-SWIGGY-8169@HDFCBANK
UPI-VIKAS-5416@OKAXIS
UPI-HOTSTAR@AXIS
ATM-WDL-HDFC-9140
UPI-ZOMATO6436@OKICICI
ATM-WDL-SBI-4080
NETFLIX.COM
UPI-IOC0494@HDFCBANK
UPI-RESTAURANT-4630@PAYTM
UPI-IOC1246@HDFCBANK
Flipkart Internet
UPI-SWIGGY1600@OKAXIS
UPI-SWIGGY8576@OKAXIS
ATM-WDL-HDFC-8030
SPOTIFY*PREMIUM
UPI-BLINKIT-6907@PAYTM
BWSSB WATER BILL
UPI-RESTAURANT-7888@PAYTM
GROWW INVEST TECH
UPI-IOC2000@HDFCBANK
UPI-SWIGGY5466@OKAXIS
UPI-SNEHA-0942@OKAXIS
UPI-SWIGGY-2664@HDFCBANK
JIOFIBER
BHARTI AIRTEL LTD
UPI-UBER-0377@HDFCBANK
UPI-UBER-5112@HDFCBANK
UPI-ZOMATO1274@OKICICI
UPI-SWIGGY4144@OKAXIS
UPI-VI-RECHARGE@HDFCBANK
UPI-KARAN-5789@OKAXIS
UPI-BLINKIT-1501@PAYTM
ZERODHA-MF SIP
UPI-SWIGGY-9575@HDFCBANK
UPI-RESTAURANT-0753@PAYTM
NEXTBILLION-GROWW
UPI-ZOMATO5010@OKICICI
UPI-BLINKIT-1469@PAYTM
UPI-SWIGGY9328@OKAXIS
NYKAA E-RETAIL
ATM-WDL-HDFC-3609
UPI-SWIGGY0226@OKAXIS
UPI-SWIGGY9600@OKAXIS
IMPS-RENT-LANDLORD-36852906
UPI-ZOMATO7344@OKICICI
UPI-ZEPTO-9191@HDFCBANK
UPI-ZOMATO9481@OKICICI
UPI-IOC2115@HDFCBANK
UPI-SWIGGY-3513@HDFCBANK
UPI-RESTAURANT-3549@PAYTM
UPI-PRIYA-8750@OKAXIS
UPI-ZOMATO5845@OKICICI
UPI-ZEPTO-6004@HDFCBANK
UPI-BLINKIT-3223@PAYTM
UPI-SWIGGY1998@OKAXIS
ATM-WDL-ICICI-6478
UPI-SWIGGY0250@OKAXIS
UPI-RESTAURANT-5630@PAYTM
UPI-SWIGGY0894@OKAXIS
UPI-ANKIT-9877@OKAXIS
UPI-SWIGGY6412@OKAXIS
UPI-SWIGGY-1791@HDFCBANK
UPI-SWIGGY5867@OKAXIS
UPI-UBER-8525@HDFCBANK
UPI-SWIGGY-4758@HDFCBANK
UPI-BLINKIT-1165@PAYTM
UPI-SWIGGY4389@OKAXIS
ATM-WDL-SBI-0237
IMPS-RENT-LANDLORD-49966195
UPI-SWIGGY8720@OKAXIS
UPI-PRIYA-0104@OKAXIS
UPI-RESTAURANT-8932@PAYTM
UPI-SWIGGY9756@OKAXIS
UPI-SWIGGY-1714@HDFCBANK
VODAFONE IDEA LTD
ATM-WDL-SBI-0279
UPI-SWIGGY-6024@HDFCBANK
UPI-ZEPTO-2913@HDFCBANK
UPI-ZOMATO5406@OKICICI
UPI-RESTAURANT-3964@PAYTM
UPI-SWIGGY5737@OKAXIS
ATM-WDL-HDFC-8253
ZERODHA SECURITIES
UPI-AMAZON-PRIME@HDFCBANK
UPI-UBER-4781@HDFCBANK
UPI-RESTAURANT-5691@PAYTM
UPI-SWIGGY2847@OKAXIS
UPI-ZOMATO9682@OKICICI
UPI-IOC5182@HDFCBANK
UPI-ANKIT-5946@OKAXIS
UPI-SWIGGY9088@OKAXIS
UPI-UBER-1392@HDFCBANK
UPI-SWIGGY9983@OKAXIS
UPI-ZEPTO-1050@HDFCBANK
UPI-ANKIT-1837@OKAXIS
IMPS-RENT-LANDLORD-35126704
UPI-SWIGGY8392@OKAXIS
UPI-ZOMATO5117@OKICICI
UPI-ZOMATO4622@OKICICI
UPI-SWIGGY1418@OKAXIS
ATM-WDL-ICICI-9135
UPI-RESTAURANT-5531@PAYTM
UPI-ANKIT-6092@OKAXIS
UPI-SWIGGY7538@OKAXIS
ATM-WDL-ICICI-4172
UPI-ZEPTO-5207@HDFCBANK
ATM-WDL-SBI-4084
UPI-ZEPTO-7106@HDFCBANK
ATM-WDL-ICICI-4739
UPI-SWIGGY6053@OKAXIS
UPI-SWIGGY-3505@HDFCBANK
UPI-SWIGGY-0015@HDFCBANK
UPI-RESTAURANT-2648@PAYTM
ATM-WDL-SBI-0874
UPI-VIKAS-1878@OKAXIS
UPI-SWIGGY6013@OKAXIS
UPI-SWIGGY-8838@HDFCBANK
UPI-VIKAS-9964@OKAXIS
UPI-RESTAURANT-7645@PAYTM
ATM-WDL-ICICI-3918
UPI-SWIGGY-9077@HDFCBANK
UPI-RESTAURANT-0874@PAYTM
ATM-WDL-ICICI-5025
UPI-SWIGGY3466@OKAXIS
UPI-BLINKIT-1828@PAYTM
UPI-UBER-3218@HDFCBANK

## Feature 2

In [237]:
vendor_keywords = {

    "Swiggy": [
        "SWIGGY",
        "BUNDL",
        "INSTAMART"
    ],

    "Zomato": [
        "ZOMATO"
    ],

    "Amazon": [
        "AMAZON",
        "AMZN"
    ],

    "Blinkit": [
        "BLINKIT",
        "GROFERS"
    ],

    "Zepto": [
        "ZEPTO",
        "KIRANAKART"
    ],

    "Flipkart": [
        "FLIPKART",
        "FKART"
    ],

    "Myntra": [
        "MYNTRA"
    ],

    "Nykaa": [
        "NYKAA",
        "FSN E-COMMERCE"
    ],

    "Uber": [
        "UBER",
        "ANI TECHNOLOGIES"
    ],

    "Ola": [
        "OLA"
    ],

    "Rapido": [
        "RAPIDO",
        "ROPPEN"
    ],

    "Starbucks": [
        "STARBUCKS"
    ],

    "Cafe Coffee Day": [
        "COFFEE DAY",
        "CCD"
    ],

    "Third Wave Coffee": [
        "THIRDWAVE",
        "TWC",
        "THIRD WAVE"
    ],

    "Truffles": [
        "TRUFFLES"
    ],

    "Restaurants": [
        "RESTAURANT",
        "DINEOUT",
        "EMPIRE RESTAURANT",
        "MEGHANA FOODS",
        "BANGALORE RESTAURANT"
    ],

    "D-Mart": [
        "DMART",
        "AVENUE SUPERMARTS"
    ],

    "BigBasket": [
        "BIGBASKET",
        "INNOVATIVE RETAIL"
    ],

    "BookMyShow": [
        "BOOKMYSHOW",
        "BMS",
        "BIGTREE"
    ],

    "Netflix": [
        "NETFLIX"
    ],

    "Spotify": [
        "SPOTIFY"
    ],

    "Disney Hotstar": [
        "HOTSTAR",
        "DISNEY",
        "STAR INDIA"
    ],

    "Airtel": [
        "AIRTEL",
        "BHARTI AIRTEL"
    ],

    "Vi": [
        "VODAFONE IDEA",
        "VI POSTPAID",
        "UPI-VI-RECHARGE"
    ],

    "Jio": [
        "RELIANCE JIO",
        "JIOFIBER",
        "JIORECHARGE"
    ],

    "BMTC": [
        "BMTC",
        "TUMMOC"
    ],

    "BESCOM": [
        "BESCOM",
        "BANGALORE ELEC SUPPLY"
    ],

    "BWSSB": [
        "BWSSB"
    ],

    "Indian Oil": [
        "INDIAN OIL",
        "IOC"
    ],

    "HP Petrol": [
        "HP PETROL"
    ],

    "BPCL": [
        "BPCL"
    ],

    "Zerodha": [
        "ZERODHA"
    ],

    "Groww": [
        "GROWW"
    ],

    "Techcrush Labs": [
        "TECHCRUSH LABS"
    ]
}

In [238]:
def extract_vendor(description):

    description = str(description).upper()

    # ATM withdrawals
    if description.startswith("ATM-WDL"):
        return "Cash Withdrawal"

    # Friend-to-friend transfers
    p2p_names = [
        "AMAN",
        "ANKIT",
        "PRIYA",
        "VIKAS",
        "NEHA",
        "SNEHA",
        "KARAN"
    ]

    if description.startswith("UPI-"):
        for name in p2p_names:
            if name in description:
                return "P2P Transfer"

    # Rent / landlord transfers
    if "RENT-LANDLORD" in description:
        return "Personal Transfer"

    # Vendor matching
    for vendor, keywords in vendor_keywords.items():

        for keyword in keywords:

            if keyword in description:
                return vendor

    # If nothing matches
    return "Uncategorised"

In [239]:
df["vendor_clean"] = df["Description"].apply(extract_vendor)

In [240]:
print("Number of unique vendors:", df["vendor_clean"].nunique())

print("\nTop 10 vendors:")
print(df["vendor_clean"].value_counts().head(10))

Number of unique vendors: 37

Top 10 vendors:
vendor_clean
Swiggy         243
Zomato         121
Uber            89
Amazon          86
Zepto           71
Ola             69
Restaurants     64
Rapido          55
Blinkit         55
Flipkart        47
Name: count, dtype: int64

In [241]:
uncategorised = df[df["vendor_clean"] == "Uncategorised"]

print("Number of uncategorised transactions:",
      len(uncategorised))

print("\nUncategorised descriptions:")
print(uncategorised["Description"].unique())

Number of uncategorised transactions: 0

Uncategorised descriptions:
[]

## Feature 3

In [242]:
category_map = {

    # Food Delivery
    "Swiggy": "Food Delivery",
    "Zomato": "Food Delivery",

    # Quick Commerce
    "Blinkit": "Quick Commerce",
    "Zepto": "Quick Commerce",

    # E-commerce
    "Amazon": "E-commerce",
    "Flipkart": "E-commerce",
    "Myntra": "E-commerce",
    "Nykaa": "E-commerce",

    # Transport
    "Uber": "Transport",
    "Ola": "Transport",
    "Rapido": "Transport",
    "BMTC": "Transport",

    # Cafe
    "Starbucks": "Cafe",
    "Cafe Coffee Day": "Cafe",
    "Third Wave Coffee": "Cafe",

    # Restaurants
    "Truffles": "Restaurants",
    "Restaurants": "Restaurants",

    # Subscriptions
    "Netflix": "Subscriptions",
    "Spotify": "Subscriptions",
    "Disney Hotstar": "Subscriptions",

    # Utilities
    "Airtel": "Utilities",
    "Vi": "Utilities",
    "Jio": "Utilities",
    "BESCOM": "Utilities",
    "BWSSB": "Utilities",

    # Groceries
    "D-Mart": "Groceries",
    "BigBasket": "Groceries",

    # Investments
    "Zerodha": "Investments",
    "Groww": "Investments",

    # Fuel
    "Indian Oil": "Fuel",
    "HP Petrol": "Fuel",
    "BPCL": "Fuel",

    # Entertainment
    "BookMyShow": "Entertainment",

    # Personal / transfer related
    "P2P Transfer": "Personal Transfer",
    "Personal Transfer": "Personal Transfer",
    "Techcrush Labs": "Personal Transfer",

    # ATM
    "Cash Withdrawal": "Cash Withdrawal"
}

In [243]:
df["category"] = df["vendor_clean"].map(category_map)

In [244]:
print("Missing categories:", df["category"].isna().sum())

Missing categories: 0

In [245]:
print(df["category"].value_counts())

category
Food Delivery        364
Transport            250
E-commerce           172
Quick Commerce       126
Cafe                  99
Restaurants           73
Utilities             43
Groceries             41
Subscriptions         31
Personal Transfer     30
Fuel                  28
Investments           23
Cash Withdrawal       17
Entertainment         13
Name: count, dtype: int64

In [246]:
vendor_category_check = (
    df[["vendor_clean", "category"]]
    .drop_duplicates()
    .sort_values("vendor_clean")
)

print(vendor_category_check.to_string(index=False))

     vendor_clean          category
           Airtel         Utilities
           Amazon        E-commerce
           BESCOM         Utilities
             BMTC         Transport
             BPCL              Fuel
            BWSSB         Utilities
        BigBasket         Groceries
          Blinkit    Quick Commerce
       BookMyShow     Entertainment
  Cafe Coffee Day              Cafe
  Cash Withdrawal   Cash Withdrawal
           D-Mart         Groceries
   Disney Hotstar     Subscriptions
         Flipkart        E-commerce
            Groww       Investments
        HP Petrol              Fuel
       Indian Oil              Fuel
              Jio         Utilities
           Myntra        E-commerce
          Netflix     Subscriptions
            Nykaa        E-commerce
              Ola         Transport
     P2P Transfer Personal Transfer
Personal Transfer Personal Transfer
           Rapido         Transport
      Restaurants       Restaurants
          Spotify     Subscriptions
        Starbucks              Cafe
           Swiggy     Food Delivery
   Techcrush Labs Personal Transfer
Third Wave Coffee              Cafe
         Truffles       Restaurants
             Uber         Transport
               Vi         Utilities
            Zepto    Quick Commerce
          Zerodha       Investments
           Zomato     Food Delivery

In [247]:
print("Total transactions:", len(df))

print("Missing categories:",
      df["category"].isna().sum())

print("\nNumber of categories:",
      df["category"].nunique())

print("\nCategory counts:")
print(df["category"].value_counts())

Total transactions: 1310
Missing categories: 0

Number of categories: 14

Category counts:
category
Food Delivery        364
Transport            250
E-commerce           172
Quick Commerce       126
Cafe                  99
Restaurants           73
Utilities             43
Groceries             41
Subscriptions         31
Personal Transfer     30
Fuel                  28
Investments           23
Cash Withdrawal       17
Entertainment         13
Name: count, dtype: int64

In [248]:
print("Missing categories:", df["category"].isna().sum())
print(df["category"].value_counts())

Missing categories: 0
category
Food Delivery        364
Transport            250
E-commerce           172
Quick Commerce       126
Cafe                  99
Restaurants           73
Utilities             43
Groceries             41
Subscriptions         31
Personal Transfer     30
Fuel                  28
Investments           23
Cash Withdrawal       17
Entertainment         13
Name: count, dtype: int64

## Feature 4--> Spending Overview

In [249]:
credits = df[df["type_clean"] == "credit"]
debits = df[df["type_clean"] == "debit"]

In [250]:
total_credits = credits["amount"].sum()
total_debits = debits["amount"].sum()

net_savings = total_credits - total_debits

savings_rate = (net_savings / total_credits) * 100

In [251]:
top_categories = (
    debits.groupby("category")["amount"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

In [252]:
print("Top 5 Categories by Spending:")
print(top_categories)

Top 5 Categories by Spending:
category
E-commerce           603877.0
Investments          248160.0
Food Delivery        159667.0
Personal Transfer    132599.0
Restaurants          117737.0
Name: amount, dtype: float64

In [253]:
top_vendors = (
    debits.groupby("vendor_clean")["amount"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

In [254]:
print("\nTop 5 Vendors by Spending:")
print(top_vendors)

Top 5 Vendors by Spending:
vendor_clean
Amazon               328530.0
Zerodha              210000.0
Flipkart             177510.0
Personal Transfer    108000.0
Swiggy               104351.0
Name: amount, dtype: float64

In [255]:
total_transactions = len(df)

In [256]:
total_transactions

1310

In [257]:
print("=" * 50)
print("           SPENDING OVERVIEW")
print("=" * 50)

print(f"Total Credits : ₹{total_credits:,.2f}")
print(f"Total Debits  : ₹{total_debits:,.2f}")
print(f"Net Savings   : ₹{net_savings:,.2f}")
print(f"Savings Rate  : {savings_rate:.2f}%")
print(f"Transactions  : {total_transactions}")

print("\nTop 5 Categories by Spending:")
for category, amount in top_categories.items():
    print(f"{category:<20} ₹{amount:,.2f}")

print("\nTop 5 Vendors by Spending:")
for vendor, amount in top_vendors.items():
    print(f"{vendor:<20} ₹{amount:,.2f}")

print("=" * 50)

==================================================
           SPENDING OVERVIEW
==================================================
Total Credits : ₹509,774.00
Total Debits  : ₹1,678,901.00
Net Savings   : ₹-1,169,127.00
Savings Rate  : -229.34%
Transactions  : 1310

Top 5 Categories by Spending:
E-commerce           ₹603,877.00
Investments          ₹248,160.00
Food Delivery        ₹159,667.00
Personal Transfer    ₹132,599.00
Restaurants          ₹117,737.00

Top 5 Vendors by Spending:
Amazon               ₹328,530.00
Zerodha              ₹210,000.00
Flipkart             ₹177,510.00
Personal Transfer    ₹108,000.00
Swiggy               ₹104,351.00
==================================================

In [258]:
print("Credits:", total_credits)
print("Debits:", total_debits)
print("Net savings:", net_savings)
print("Savings rate:", savings_rate)

Credits: 509774.0
Debits: 1678901.0
Net savings: -1169127.0
Savings rate: -229.34221831635196

In [259]:
print("Type-wise summary:")
print(
    df.groupby("type_clean")["amount"]
      .agg(["count", "sum", "mean", "min", "max"])
)

Type-wise summary:
            count        sum          mean      min      max
type_clean
credit          6   509774.0  84962.333333  84701.0  85492.0
debit        1304  1678901.0   1287.500767     10.0  22008.0

In [260]:
print("\nLargest transactions:")
print(
    df.sort_values("amount", ascending=False)
      [["Description", "Type", "type_clean", "Amount", "amount"]]
      .head(20)
      .to_string(index=False)
)

Largest transactions:
                     Description  Type type_clean     Amount  amount
NEFT-TECHCRUSH LABS-SALARY MAY24    CR     credit     ₹85492 85492.0
NEFT-TECHCRUSH LABS-SALARY MAY24    CR     credit      85393 85393.0
NEFT-TECHCRUSH LABS-SALARY MAY24    CR     credit     ₹84736 84736.0
NEFT-TECHCRUSH LABS-SALARY MAY24    CR     credit     ₹84728 84728.0
NEFT-TECHCRUSH LABS-SALARY MAY24    CR     credit  84,724.00 84724.0
NEFT-TECHCRUSH LABS-SALARY MAY24    CR     credit Rs. 84,701 84701.0
            AMAZONIN MARKETPLACE    DR      debit     ₹22008 22008.0
          UPI-AMAZONPAY@HDFCBANK Debit      debit     ₹21986 21986.0
          UPI-AMAZONPAY@HDFCBANK Debit      debit  19,917.00 19917.0
                       AMAZON IN Debit      debit      18273 18273.0
     IMPS-RENT-LANDLORD-36852906 Debit      debit Rs. 18,000 18000.0
     IMPS-RENT-LANDLORD-35126704 Debit      debit     ₹18000 18000.0
     IMPS-RENT-LANDLORD-39598076 Debit      debit Rs. 18,000 18000.0
     IMPS-RENT-LANDLORD-49966195 Debit      debit  18,000.00 18000.0
     IMPS-RENT-LANDLORD-51148088    DR      debit      18000 18000.0
     IMPS-RENT-LANDLORD-75500265 Debit      debit  18,000.00 18000.0
           UPI-FLIPKART@HDFCBANK    DR      debit      17831 17831.0
                Amazon Pay India    DR      debit      17504 17504.0
           UPI-FLIPKART@HDFCBANK Debit      debit  16,369.00 16369.0
                  FLIPKART INDIA    DR      debit      16260 16260.0

In [261]:
print("\nAmount statistics:")
print(df["amount"].describe())

Amount statistics:
count     1310.000000
mean      1670.744275
std       6306.346647
min         10.000000
25%        295.250000
50%        477.000000
75%       1009.750000
max      85492.000000
Name: amount, dtype: float64

In [262]:
debit_by_category = (
    df[df["type_clean"] == "debit"]
    .groupby("category")["amount"]
    .agg(["count", "sum"])
    .sort_values("sum", ascending=False)
)

print(debit_by_category)

                   count       sum
category
E-commerce           172  603877.0
Investments           23  248160.0
Food Delivery        364  159667.0
Personal Transfer     24  132599.0
Restaurants           73  117737.0
Fuel                  28   89303.0
Quick Commerce       126   65054.0
Groceries             41   59407.0
Transport            250   57474.0
Cash Withdrawal       17   45500.0
Utilities             43   41914.0
Cafe                  99   31445.0
Subscriptions         31   18471.0
Entertainment         13    8293.0

In [263]:
special_categories = [
    "Personal Transfer",
    "Cash Withdrawal",
    "Investments"
]

print(
    df[
        (df["type_clean"] == "debit") &
        (df["category"].isin(special_categories))
    ]
    .groupby("category")["amount"]
    .agg(["count", "sum"])
)

                   count       sum
category
Cash Withdrawal       17   45500.0
Investments           23  248160.0
Personal Transfer     24  132599.0

In [264]:
print("Total rows:", len(df))
print("Debit rows:", (df["type_clean"] == "debit").sum())
print("Credit rows:", (df["type_clean"] == "credit").sum())

Total rows: 1310
Debit rows: 1304
Credit rows: 6

In [265]:
debits = df[df["type_clean"] == "debit"]

In [266]:
debit_by_category = (
    df[df["type_clean"] == "debit"]
    .groupby("category")["amount"]
    .agg(["count", "sum"])
    .sort_values("sum", ascending=False)
)

print(debit_by_category)

                   count       sum
category
E-commerce           172  603877.0
Investments           23  248160.0
Food Delivery        364  159667.0
Personal Transfer     24  132599.0
Restaurants           73  117737.0
Fuel                  28   89303.0
Quick Commerce       126   65054.0
Groceries             41   59407.0
Transport            250   57474.0
Cash Withdrawal       17   45500.0
Utilities             43   41914.0
Cafe                  99   31445.0
Subscriptions         31   18471.0
Entertainment         13    8293.0

In [267]:
print(
    df[
        (df["type_clean"] == "debit") &
        (df["category"].isin([
            "Personal Transfer",
            "Cash Withdrawal",
            "Investments"
        ]))
    ]
    .groupby("category")["amount"]
    .agg(["count", "sum"])
)

                   count       sum
category
Cash Withdrawal       17   45500.0
Investments           23  248160.0
Personal Transfer     24  132599.0

In [268]:
print("Debit total:", df.loc[df["type_clean"] == "debit", "amount"].sum())

print("\nNumber of debit transactions:",
      (df["type_clean"] == "debit").sum())

print("\nTotal amount:",
      df["amount"].sum())

print("\nCredits:",
      df.loc[df["type_clean"] == "credit", "amount"].sum())

Debit total: 1678901.0

Number of debit transactions: 1304

Total amount: 2188675.0

Credits: 509774.0

In [269]:
print("Zerodha transactions:")
print(
    df[df["vendor_clean"] == "Zerodha"]
    [["Date", "Description", "Type", "amount", "category"]]
    .to_string(index=False)
)

Zerodha transactions:
       Date           Description  Type  amount    category
   07/01/24 UPI-ZERODHA-COIN@AXIS Debit 15000.0 Investments
19 Jan 2024  NEFT ZERODHA BROKING Debit 15000.0 Investments
 2024-02-08     IMPS ZERODHA-COIN    DR 15000.0 Investments
  02-Mar-24     IMPS ZERODHA-COIN    DR 15000.0 Investments
   07/03/24 UPI-ZERODHA-COIN@AXIS    DR 15000.0 Investments
 2024-03-12     IMPS ZERODHA-COIN    DR 15000.0 Investments
 2024-03-26        ZERODHA-MF SIP    DR 15000.0 Investments
 2024-04-08     IMPS ZERODHA-COIN    DR 15000.0 Investments
 2024-04-13     IMPS ZERODHA-COIN Debit 15000.0 Investments
  17-Apr-24 UPI-ZERODHA-COIN@AXIS Debit 15000.0 Investments
 2024-05-07     IMPS ZERODHA-COIN Debit 15000.0 Investments
   18/05/24 UPI-ZERODHA-COIN@AXIS Debit 15000.0 Investments
 2024-05-22    ZERODHA SECURITIES    DR 15000.0 Investments
   08/06/24        ZERODHA-MF SIP Debit 15000.0 Investments

In [270]:
print("\nAmazon transactions:")
print(
    df[df["vendor_clean"] == "Amazon"]
    [["Date", "Description", "Type", "amount", "category"]]
    .sort_values("amount", ascending=False)
    .to_string(index=False)
)

Amazon transactions:
       Date               Description  Type  amount   category
26 Jun 2024      AMAZONIN MARKETPLACE    DR 22008.0 E-commerce
   07/02/24    UPI-AMAZONPAY@HDFCBANK Debit 21986.0 E-commerce
05 Mar 2024    UPI-AMAZONPAY@HDFCBANK Debit 19917.0 E-commerce
  02-Mar-24                 AMAZON IN Debit 18273.0 E-commerce
25 Jun 2024          Amazon Pay India    DR 17504.0 E-commerce
   31/03/24      AMAZONIN MARKETPLACE Debit 15953.0 E-commerce
  30-Apr-24          Amazon Pay India    DR 14886.0 E-commerce
  05-Jun-24          Amazon Pay India Debit 14874.0 E-commerce
 2024-02-17    UPI-AMAZONPAY@HDFCBANK    DR 13674.0 E-commerce
  14-May-24      AMAZONIN MARKETPLACE Debit  4485.0 E-commerce
  17-Jan-24                 AMAZON IN Debit  4473.0 E-commerce
15 Feb 2024    UPI-AMAZONPAY@HDFCBANK    DR  4373.0 E-commerce
19 Mar 2024    UPI-AMAZONPAY@HDFCBANK    DR  4304.0 E-commerce
   20/02/24                 AMAZON IN    DR  4280.0 E-commerce
28 Mar 2024          Amazon Pay India    DR  4255.0 E-commerce
  20-May-24    UPI-AMAZONPAY@HDFCBANK    DR  4244.0 E-commerce
   05/01/24    UPI-AMAZONPAY@HDFCBANK Debit  4208.0 E-commerce
 2024-01-12          Amazon Pay India    DR  4092.0 E-commerce
  11-Jan-24                 AMAZON IN Debit  4092.0 E-commerce
  20-Jan-24      AMAZONIN MARKETPLACE    DR  4037.0 E-commerce
02 Jun 2024        AMAZON SELLER SVCS Debit  3970.0 E-commerce
   09/06/24              AMZN-INTPYMT Debit  3888.0 E-commerce
 2024-02-16                 AMAZON IN    DR  3764.0 E-commerce
21 Jun 2024          Amazon Pay India Debit  3643.0 E-commerce
   24/01/24    UPI-AMAZONPAY@HDFCBANK Debit  3363.0 E-commerce
  07-Jun-24          Amazon Pay India    DR  3284.0 E-commerce
 2024-01-14          Amazon Pay India    DR  3256.0 E-commerce
   24/01/24              AMZN-INTPYMT Debit  3208.0 E-commerce
   15/06/24          Amazon Pay India    DR  3179.0 E-commerce
  04-Jun-24              AMZN-INTPYMT Debit  3066.0 E-commerce
  28-Feb-24          Amazon Pay India Debit  2995.0 E-commerce
  13-Feb-24          Amazon Pay India    DR  2966.0 E-commerce
   26/03/24          Amazon Pay India    DR  2849.0 E-commerce
29 Apr 2024        AMAZON SELLER SVCS Debit  2816.0 E-commerce
   08/01/24        AMAZON SELLER SVCS Debit  2814.0 E-commerce
 2024-05-13      AMAZONIN MARKETPLACE    DR  2771.0 E-commerce
  13-Mar-24      AMAZONIN MARKETPLACE    DR  2732.0 E-commerce
12 Jan 2024    UPI-AMAZONPAY@HDFCBANK    DR  2717.0 E-commerce
  22-Jun-24      AMAZONIN MARKETPLACE Debit  2655.0 E-commerce
27 Mar 2024      AMAZONIN MARKETPLACE Debit  2619.0 E-commerce
 2024-04-16                 AMAZON IN    DR  2599.0 E-commerce
   10/02/24          Amazon Pay India    DR  2592.0 E-commerce
28 Mar 2024      AMAZONIN MARKETPLACE Debit  2553.0 E-commerce
  16-Jun-24        AMAZON SELLER SVCS Debit  2519.0 E-commerce
   20/02/24              AMZN-INTPYMT    DR  2477.0 E-commerce
 2024-01-01        AMAZON SELLER SVCS Debit  2462.0 E-commerce
  19-May-24              AMZN-INTPYMT Debit  2254.0 E-commerce
  06-Mar-24              AMZN-INTPYMT    DR  2051.0 E-commerce
   01/06/24          Amazon Pay India Debit  1802.0 E-commerce
   11/02/24                 AMAZON IN Debit  1781.0 E-commerce
   08/03/24      AMAZONIN MARKETPLACE Debit  1685.0 E-commerce
  15-Mar-24              AMZN-INTPYMT    DR  1555.0 E-commerce
   31/01/24      AMAZONIN MARKETPLACE Debit  1541.0 E-commerce
 2024-01-30              AMZN-INTPYMT    DR  1500.0 E-commerce
   21/03/24      AMAZONIN MARKETPLACE    DR  1498.0 E-commerce
25 Jan 2024                AMZN PRIME    DR  1489.0 E-commerce
  18-Feb-24          Amazon Pay India Debit  1475.0 E-commerce
   25/01/24              AMZN-INTPYMT Debit  1410.0 E-commerce
  17-Mar-24                AMZN PRIME Debit  1322.0 E-commerce
  08-Mar-24          Amazon Pay India Debit  1255.0 E-commerce
  25-Feb-24        AMAZON PRIME VIDEO    DR  1238.0 E-commerce
  11-May-24        AMAZON SELLER SVCS Debit  1235.0 E-commerce
05 Mar 2024                AMZN PRIME    DR  1153.0 E-commerce
 2024-03-31                AMZN PRIME Debit  1142.0 E-commerce
 2024-04-25        AMAZON PRIME VIDEO    DR  1121.0 E-commerce
   27/04/24                 AMAZON IN Debit  1086.0 E-commerce
 2024-04-16      AMAZONIN MARKETPLACE Debit  1071.0 E-commerce
   25/06/24        AMAZON PRIME VIDEO Debit  1042.0 E-commerce
15 May 2024          Amazon Pay India Debit  1034.0 E-commerce
   23/01/24        AMAZON SELLER SVCS Debit  1031.0 E-commerce
 2024-04-02              AMZN-INTPYMT Debit   996.0 E-commerce
  07-Jun-24              AMZN-INTPYMT    DR   972.0 E-commerce
   16/06/24      AMAZONIN MARKETPLACE Debit   945.0 E-commerce
14 Apr 2024          Amazon Pay India    DR   926.0 E-commerce
 2024-06-18        AMAZON SELLER SVCS    DR   883.0 E-commerce
 2024-04-28                 AMAZON IN    DR   880.0 E-commerce
 2024-03-25        AMAZON PRIME VIDEO Debit   826.0 E-commerce
   17/06/24    UPI-AMAZONPAY@HDFCBANK    DR   740.0 E-commerce
  29-Feb-24    UPI-AMAZONPAY@HDFCBANK Debit   663.0 E-commerce
   18/03/24    UPI-AMAZONPAY@HDFCBANK Debit   622.0 E-commerce
 2024-05-14                AMZN PRIME    DR   585.0 E-commerce
  09-Apr-24        AMAZON SELLER SVCS Debit   531.0 E-commerce
  04-May-24                 AMAZON IN    DR   505.0 E-commerce
   26/03/24          Amazon Pay India    DR   486.0 E-commerce
   13/06/24      AMAZONIN MARKETPLACE Debit   334.0 E-commerce
   25/05/24 UPI-AMAZON-PRIME@HDFCBANK Debit   190.0 E-commerce

In [271]:
print("\nAmazon transactions:")
print(
    df[df["vendor_clean"] == "Amazon"]
    [["Date", "Description", "Type", "amount", "category"]]
    .sort_values("amount", ascending=False)
    .to_string(index=False)
)

Amazon transactions:
       Date               Description  Type  amount   category
26 Jun 2024      AMAZONIN MARKETPLACE    DR 22008.0 E-commerce
   07/02/24    UPI-AMAZONPAY@HDFCBANK Debit 21986.0 E-commerce
05 Mar 2024    UPI-AMAZONPAY@HDFCBANK Debit 19917.0 E-commerce
  02-Mar-24                 AMAZON IN Debit 18273.0 E-commerce
25 Jun 2024          Amazon Pay India    DR 17504.0 E-commerce
   31/03/24      AMAZONIN MARKETPLACE Debit 15953.0 E-commerce
  30-Apr-24          Amazon Pay India    DR 14886.0 E-commerce
  05-Jun-24          Amazon Pay India Debit 14874.0 E-commerce
 2024-02-17    UPI-AMAZONPAY@HDFCBANK    DR 13674.0 E-commerce
  14-May-24      AMAZONIN MARKETPLACE Debit  4485.0 E-commerce
  17-Jan-24                 AMAZON IN Debit  4473.0 E-commerce
15 Feb 2024    UPI-AMAZONPAY@HDFCBANK    DR  4373.0 E-commerce
19 Mar 2024    UPI-AMAZONPAY@HDFCBANK    DR  4304.0 E-commerce
   20/02/24                 AMAZON IN    DR  4280.0 E-commerce
28 Mar 2024          Amazon Pay India    DR  4255.0 E-commerce
  20-May-24    UPI-AMAZONPAY@HDFCBANK    DR  4244.0 E-commerce
   05/01/24    UPI-AMAZONPAY@HDFCBANK Debit  4208.0 E-commerce
 2024-01-12          Amazon Pay India    DR  4092.0 E-commerce
  11-Jan-24                 AMAZON IN Debit  4092.0 E-commerce
  20-Jan-24      AMAZONIN MARKETPLACE    DR  4037.0 E-commerce
02 Jun 2024        AMAZON SELLER SVCS Debit  3970.0 E-commerce
   09/06/24              AMZN-INTPYMT Debit  3888.0 E-commerce
 2024-02-16                 AMAZON IN    DR  3764.0 E-commerce
21 Jun 2024          Amazon Pay India Debit  3643.0 E-commerce
   24/01/24    UPI-AMAZONPAY@HDFCBANK Debit  3363.0 E-commerce
  07-Jun-24          Amazon Pay India    DR  3284.0 E-commerce
 2024-01-14          Amazon Pay India    DR  3256.0 E-commerce
   24/01/24              AMZN-INTPYMT Debit  3208.0 E-commerce
   15/06/24          Amazon Pay India    DR  3179.0 E-commerce
  04-Jun-24              AMZN-INTPYMT Debit  3066.0 E-commerce
  28-Feb-24          Amazon Pay India Debit  2995.0 E-commerce
  13-Feb-24          Amazon Pay India    DR  2966.0 E-commerce
   26/03/24          Amazon Pay India    DR  2849.0 E-commerce
29 Apr 2024        AMAZON SELLER SVCS Debit  2816.0 E-commerce
   08/01/24        AMAZON SELLER SVCS Debit  2814.0 E-commerce
 2024-05-13      AMAZONIN MARKETPLACE    DR  2771.0 E-commerce
  13-Mar-24      AMAZONIN MARKETPLACE    DR  2732.0 E-commerce
12 Jan 2024    UPI-AMAZONPAY@HDFCBANK    DR  2717.0 E-commerce
  22-Jun-24      AMAZONIN MARKETPLACE Debit  2655.0 E-commerce
27 Mar 2024      AMAZONIN MARKETPLACE Debit  2619.0 E-commerce
 2024-04-16                 AMAZON IN    DR  2599.0 E-commerce
   10/02/24          Amazon Pay India    DR  2592.0 E-commerce
28 Mar 2024      AMAZONIN MARKETPLACE Debit  2553.0 E-commerce
  16-Jun-24        AMAZON SELLER SVCS Debit  2519.0 E-commerce
   20/02/24              AMZN-INTPYMT    DR  2477.0 E-commerce
 2024-01-01        AMAZON SELLER SVCS Debit  2462.0 E-commerce
  19-May-24              AMZN-INTPYMT Debit  2254.0 E-commerce
  06-Mar-24              AMZN-INTPYMT    DR  2051.0 E-commerce
   01/06/24          Amazon Pay India Debit  1802.0 E-commerce
   11/02/24                 AMAZON IN Debit  1781.0 E-commerce
   08/03/24      AMAZONIN MARKETPLACE Debit  1685.0 E-commerce
  15-Mar-24              AMZN-INTPYMT    DR  1555.0 E-commerce
   31/01/24      AMAZONIN MARKETPLACE Debit  1541.0 E-commerce
 2024-01-30              AMZN-INTPYMT    DR  1500.0 E-commerce
   21/03/24      AMAZONIN MARKETPLACE    DR  1498.0 E-commerce
25 Jan 2024                AMZN PRIME    DR  1489.0 E-commerce
  18-Feb-24          Amazon Pay India Debit  1475.0 E-commerce
   25/01/24              AMZN-INTPYMT Debit  1410.0 E-commerce
  17-Mar-24                AMZN PRIME Debit  1322.0 E-commerce
  08-Mar-24          Amazon Pay India Debit  1255.0 E-commerce
  25-Feb-24        AMAZON PRIME VIDEO    DR  1238.0 E-commerce
  11-May-24        AMAZON SELLER SVCS Debit  1235.0 E-commerce
05 Mar 2024                AMZN PRIME    DR  1153.0 E-commerce
 2024-03-31                AMZN PRIME Debit  1142.0 E-commerce
 2024-04-25        AMAZON PRIME VIDEO    DR  1121.0 E-commerce
   27/04/24                 AMAZON IN Debit  1086.0 E-commerce
 2024-04-16      AMAZONIN MARKETPLACE Debit  1071.0 E-commerce
   25/06/24        AMAZON PRIME VIDEO Debit  1042.0 E-commerce
15 May 2024          Amazon Pay India Debit  1034.0 E-commerce
   23/01/24        AMAZON SELLER SVCS Debit  1031.0 E-commerce
 2024-04-02              AMZN-INTPYMT Debit   996.0 E-commerce
  07-Jun-24              AMZN-INTPYMT    DR   972.0 E-commerce
   16/06/24      AMAZONIN MARKETPLACE Debit   945.0 E-commerce
14 Apr 2024          Amazon Pay India    DR   926.0 E-commerce
 2024-06-18        AMAZON SELLER SVCS    DR   883.0 E-commerce
 2024-04-28                 AMAZON IN    DR   880.0 E-commerce
 2024-03-25        AMAZON PRIME VIDEO Debit   826.0 E-commerce
   17/06/24    UPI-AMAZONPAY@HDFCBANK    DR   740.0 E-commerce
  29-Feb-24    UPI-AMAZONPAY@HDFCBANK Debit   663.0 E-commerce
   18/03/24    UPI-AMAZONPAY@HDFCBANK Debit   622.0 E-commerce
 2024-05-14                AMZN PRIME    DR   585.0 E-commerce
  09-Apr-24        AMAZON SELLER SVCS Debit   531.0 E-commerce
  04-May-24                 AMAZON IN    DR   505.0 E-commerce
   26/03/24          Amazon Pay India    DR   486.0 E-commerce
   13/06/24      AMAZONIN MARKETPLACE Debit   334.0 E-commerce
   25/05/24 UPI-AMAZON-PRIME@HDFCBANK Debit   190.0 E-commerce

In [272]:
print("Credits:", total_credits)
print("Debits:", total_debits)
print("Net savings:", net_savings)
print("Savings rate:", savings_rate)

Credits: 509774.0
Debits: 1678901.0
Net savings: -1169127.0
Savings rate: -229.34221831635196

## Feature 5--Monthly Trend Analysis

In [273]:
df["month"] = df["date"].dt.month

print(df[["date", "month"]].head())

        date  month
0 2024-01-01      1
1 2024-01-01      1
2 2024-01-01      1
3 2024-01-01      1
4 2024-01-01      1

In [274]:
monthly_spending = df[df["type_clean"] == "debit"].pivot_table(
    values="amount",
    index="category",
    columns="month",
    aggfunc="sum",
    fill_value=0
)

In [275]:
print(sorted(df["month"].unique()))

[np.int32(1), np.int32(2), np.int32(3), np.int32(4), np.int32(5), np.int32(6)]

In [276]:
print(df["date"].min())
print(df["date"].max())

2024-01-01 00:00:00
2024-06-30 00:00:00

In [277]:
month_names = {
    1: "Jan",
    2: "Feb",
    3: "Mar",
    4: "Apr",
    5: "May",
    6: "Jun"
}

df["month_name"] = df["date"].dt.month.map(month_names)

In [278]:
monthly_spending = df[
    df["type_clean"] == "debit"
].pivot_table(
    values="amount",
    index="category",
    columns="month_name",
    aggfunc="sum",
    fill_value=0
)

In [279]:
month_order = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]

monthly_spending = monthly_spending.reindex(
    columns=month_order,
    fill_value=0
)

In [280]:
print(monthly_spending)

month_name             Jan      Feb       Mar      Apr      May       Jun
category
Cafe                3690.0   4273.0    5448.0   6564.0   5668.0    5802.0
Cash Withdrawal     2000.0   5000.0    8000.0   5500.0   8000.0   17000.0
E-commerce         98623.0  94011.0  108215.0  69219.0  95776.0  138033.0
Entertainment       1263.0    474.0    2418.0   2224.0      0.0    1914.0
Food Delivery      23692.0  26458.0   25918.0  30092.0  26598.0   26909.0
Fuel               30322.0   2079.0   26164.0  18718.0   9138.0    2882.0
Groceries          17649.0   8571.0    6289.0  11748.0   9718.0    5432.0
Investments        38432.0  15000.0   68644.0  54126.0  48628.0   23330.0
Personal Transfer  25852.0  22285.0   22275.0  18663.0  21412.0   22112.0
Quick Commerce      9995.0  12459.0   12911.0   9534.0  10757.0    9398.0
Restaurants        16320.0  21772.0   28313.0   7711.0  22286.0   21335.0
Subscriptions       2767.0   4628.0    3509.0   2168.0   1844.0    3555.0
Transport          11005.0  10191.0    6857.0   9284.0  13141.0    6996.0
Utilities           9157.0   6870.0    5497.0   5831.0   4340.0   10219.0

In [281]:
print(sorted(df["month"].unique()))

[np.int32(1), np.int32(2), np.int32(3), np.int32(4), np.int32(5), np.int32(6)]

In [282]:
print(df["date"].min())
print(df["date"].max())

2024-01-01 00:00:00
2024-06-30 00:00:00

In [283]:
growth = {}

for category in monthly_spending.index:

    first_month = monthly_spending.loc[category, "Jan"]
    last_month = monthly_spending.loc[category, "Jun"]

    if first_month != 0:
        growth[category] = (
            (last_month - first_month) / first_month
        ) * 100

growth = pd.Series(growth).sort_values(ascending=False)

print("Jan to Jun growth:")
print(growth)

Jan to Jun growth:
Cash Withdrawal      750.000000
Cafe                  57.235772
Entertainment         51.543943
E-commerce            39.960253
Restaurants           30.729167
Subscriptions         28.478497
Food Delivery         13.578423
Utilities             11.597685
Quick Commerce        -5.972986
Personal Transfer    -14.466966
Transport            -36.428896
Investments          -39.295379
Groceries            -69.222052
Fuel                 -90.495350
dtype: float64

In [284]:
biggest_growth_category = growth.idxmax()
biggest_growth_percent = growth.max()

biggest_decline_category = growth.idxmin()
biggest_decline_percent = growth.min()

print("\nBiggest growth:")
print(
    f"{biggest_growth_category}: "
    f"{biggest_growth_percent:.2f}%"
)

print("\nBiggest decline:")
print(
    f"{biggest_decline_category}: "
    f"{biggest_decline_percent:.2f}%"
)

Biggest growth:
Cash Withdrawal: 750.00%

Biggest decline:
Fuel: -90.50%

In [285]:
print("=" * 60)
print("FEATURE 5 - MONTHLY TREND ANALYSIS")
print("=" * 60)

print("\nMonthly Spending:")
print(monthly_spending)

print("\nJan to Jun Growth:")
print(growth)

print("\nBiggest Growth:")
print(
    f"{biggest_growth_category} "
    f"({biggest_growth_percent:.2f}%)"
)

print("\nBiggest Decline:")
print(
    f"{biggest_decline_category} "
    f"({biggest_decline_percent:.2f}%)"
)

print("=" * 60)

============================================================
FEATURE 5 - MONTHLY TREND ANALYSIS
============================================================

Monthly Spending:
month_name             Jan      Feb       Mar      Apr      May       Jun
category
Cafe                3690.0   4273.0    5448.0   6564.0   5668.0    5802.0
Cash Withdrawal     2000.0   5000.0    8000.0   5500.0   8000.0   17000.0
E-commerce         98623.0  94011.0  108215.0  69219.0  95776.0  138033.0
Entertainment       1263.0    474.0    2418.0   2224.0      0.0    1914.0
Food Delivery      23692.0  26458.0   25918.0  30092.0  26598.0   26909.0
Fuel               30322.0   2079.0   26164.0  18718.0   9138.0    2882.0
Groceries          17649.0   8571.0    6289.0  11748.0   9718.0    5432.0
Investments        38432.0  15000.0   68644.0  54126.0  48628.0   23330.0
Personal Transfer  25852.0  22285.0   22275.0  18663.0  21412.0   22112.0
Quick Commerce      9995.0  12459.0   12911.0   9534.0  10757.0    9398.0
Restaurants        16320.0  21772.0   28313.0   7711.0  22286.0   21335.0
Subscriptions       2767.0   4628.0    3509.0   2168.0   1844.0    3555.0
Transport          11005.0  10191.0    6857.0   9284.0  13141.0    6996.0
Utilities           9157.0   6870.0    5497.0   5831.0   4340.0   10219.0

Jan to Jun Growth:
Cash Withdrawal      750.000000
Cafe                  57.235772
Entertainment         51.543943
E-commerce            39.960253
Restaurants           30.729167
Subscriptions         28.478497
Food Delivery         13.578423
Utilities             11.597685
Quick Commerce        -5.972986
Personal Transfer    -14.466966
Transport            -36.428896
Investments          -39.295379
Groceries            -69.222052
Fuel                 -90.495350
dtype: float64

Biggest Growth:
Cash Withdrawal (750.00%)

Biggest Decline:
Fuel (-90.50%)
============================================================

## Feature 6 — Time-of-Day Patterns.

In [286]:
df["hour"] = df["Time"].str[:2].astype(int)

print(df[["Time", "hour"]].head(10))

    Time  hour
0  03:11     3
1  05:44     5
2  09:35     9
3  14:07    14
4  14:23    14
5  14:48    14
6  14:50    14
7  21:44    21
8  05:18     5
9  06:55     6

In [287]:
def get_time_period(hour):

    if 5 <= hour < 12:
        return "Morning"

    elif 12 <= hour < 17:
        return "Afternoon"

    elif 17 <= hour < 21:
        return "Evening"

    else:
        return "Night"

In [288]:
df["time_period"] = df["hour"].apply(get_time_period)

In [289]:
print(df["time_period"].value_counts())

time_period
Morning      354
Evening      340
Afternoon    314
Night        302
Name: count, dtype: int64

In [290]:
time_matrix = df[df["type_clean"] == "debit"].pivot_table(
    values="amount",
    index="category",
    columns="hour",
    aggfunc="sum",
    fill_value=0
)

In [291]:
time_matrix = time_matrix.reindex(
    columns=range(24),
    fill_value=0
)

In [292]:
print(time_matrix)

hour                    0        1        2        3        4        5   \
category
Cafe                 872.0    549.0      0.0    316.0      0.0      0.0
Cash Withdrawal        0.0      0.0      0.0      0.0      0.0      0.0
E-commerce         18650.0   9801.0  10246.0  14865.0  12018.0  17258.0
Entertainment        562.0    620.0      0.0      0.0      0.0      0.0
Food Delivery       1515.0   3017.0   1374.0   2135.0   2618.0   3488.0
Fuel                2675.0   2048.0      0.0    676.0   2010.0   2105.0
Groceries           3895.0   1536.0   2352.0  10064.0   1169.0      0.0
Investments         4883.0  15000.0      0.0      0.0  18834.0   4496.0
Personal Transfer      0.0      0.0      0.0      0.0      0.0      0.0
Quick Commerce       859.0   1402.0    697.0    732.0    768.0   1448.0
Restaurants         1411.0    960.0   1336.0   1714.0      0.0   2126.0
Subscriptions          0.0   1038.0   1295.0   4029.0   4685.0    745.0
Transport            706.0    260.0    358.0    337.0    577.0   2005.0
Utilities           1941.0   2651.0   2625.0      0.0   1222.0      0.0

hour                    6        7       8        9   ...       14       15  \
category                                              ...
Cafe                 179.0    480.0  2668.0   1986.0  ...   1332.0   2085.0
Cash Withdrawal        0.0      0.0  4000.0  10500.0  ...   1000.0      0.0
E-commerce          9249.0  10916.0  6537.0  40724.0  ...  72584.0   7700.0
Entertainment          0.0    311.0  1463.0      0.0  ...      0.0      0.0
Food Delivery        238.0   1498.0  3737.0   6366.0  ...   4567.0   8315.0
Fuel                   0.0      0.0  1727.0   2283.0  ...   7828.0  11937.0
Groceries           5265.0      0.0  2430.0   5694.0  ...   2237.0      0.0
Investments        37717.0      0.0     0.0   4737.0  ...      0.0      0.0
Personal Transfer      0.0      0.0   329.0   2425.0  ...  19828.0      0.0
Quick Commerce       787.0    252.0  1835.0   5491.0  ...   3407.0   3014.0
Restaurants          859.0      0.0  8037.0    702.0  ...    385.0    769.0
Subscriptions        657.0   1157.0     0.0      0.0  ...   1473.0      0.0
Transport            555.0   3924.0  4311.0   2789.0  ...   2096.0   3767.0
Utilities              0.0   1400.0  4325.0   3004.0  ...   4273.0   2060.0

hour                    16       17       18       19       20       21  \
category
Cafe                3079.0   3552.0   2562.0    584.0   1491.0      0.0
Cash Withdrawal     5000.0      0.0   5000.0      0.0   1000.0   1000.0
E-commerce         52046.0  35378.0  35272.0  12668.0  51190.0  35095.0
Entertainment       1881.0      0.0   1270.0    417.0   1426.0      0.0
Food Delivery       5674.0   3951.0  14287.0  17300.0  18656.0  12805.0
Fuel                9343.0      0.0   1950.0   8351.0    705.0  11845.0
Groceries              0.0      0.0    910.0   1248.0   2566.0   3688.0
Investments            0.0      0.0  15000.0   4476.0  15000.0      0.0
Personal Transfer   2361.0   3586.0    864.0   1295.0   2548.0   3004.0
Quick Commerce      5488.0    948.0   4524.0   6992.0   7035.0   6019.0
Restaurants        11798.0   4094.0  10788.0   8615.0  27663.0   6348.0
Subscriptions          0.0      0.0      0.0   1435.0      0.0    119.0
Transport           3325.0   3751.0   3448.0   3759.0   4647.0   1622.0
Utilities            602.0   1344.0   5468.0    708.0   4162.0      0.0

hour                    22       23
category
Cafe                   0.0    764.0
Cash Withdrawal     4000.0      0.0
E-commerce         16182.0  15403.0
Entertainment        343.0      0.0
Food Delivery       9283.0   5568.0
Fuel                   0.0   1641.0
Groceries              0.0   2536.0
Investments        15000.0  18628.0
Personal Transfer   2185.0      0.0
Quick Commerce      3405.0    763.0
Restaurants         2782.0   1256.0
Subscriptions          0.0      0.0
Transport           1852.0   1458.0
Utilities            835.0    386.0

[14 rows x 24 columns]

In [293]:
hourly_spending = time_matrix.sum(axis=0)

busiest_hour = hourly_spending.idxmax()
busiest_hour_amount = hourly_spending.max()

print("Busiest spending hour:",
      busiest_hour)

print("Amount spent:",
      busiest_hour_amount)

Busiest spending hour: 10
Amount spent: 140526.0

In [294]:
period_spending = (
    df[df["type_clean"] == "debit"]
    .groupby("time_period")["amount"]
    .sum()
    .sort_values(ascending=False)
)

print("\nSpending by time period:")
print(period_spending)

Spending by time period:
time_period
Morning      501130.0
Afternoon    452169.0
Evening      363884.0
Night        361718.0
Name: amount, dtype: float64

In [295]:
period_category = (
    df[df["type_clean"] == "debit"]
    .groupby(["time_period", "category"])["amount"]
    .sum()
    .reset_index()
)

for period in ["Morning", "Afternoon", "Evening", "Night"]:

    data = period_category[
        period_category["time_period"] == period
    ].sort_values("amount", ascending=False)

    if len(data) > 0:
        top_category = data.iloc[0]

        print(
            f"{period}: "
            f"{top_category['category']} "
            f"₹{top_category['amount']:,.2f}"
        )

Morning: E-commerce ₹157,003.00
Afternoon: E-commerce ₹180,106.00
Evening: E-commerce ₹134,508.00
Night: E-commerce ₹132,260.00

In [296]:
swiggy_debits = df[
    (df["type_clean"] == "debit") &
    (df["vendor_clean"] == "Swiggy")
]

late_night_swiggy = swiggy_debits[
    (swiggy_debits["hour"] >= 21) |
    (swiggy_debits["hour"] <= 1)
]

swiggy_percentage = (
    len(late_night_swiggy) /
    len(swiggy_debits)
) * 100

print(
    f"Swiggy transactions between 9 PM and 1 AM: "
    f"{swiggy_percentage:.2f}%"
)

Swiggy transactions between 9 PM and 1 AM: 21.81%

In [297]:
cafe_debits = df[
    (df["type_clean"] == "debit") &
    (df["category"] == "Cafe")
]

morning_cafe = cafe_debits[
    (cafe_debits["hour"] >= 8) &
    (cafe_debits["hour"] <= 11)
]

cafe_percentage = (
    len(morning_cafe) /
    len(cafe_debits)
) * 100

print(
    f"Cafe transactions between 8 AM and 11 AM: "
    f"{cafe_percentage:.2f}%"
)

Cafe transactions between 8 AM and 11 AM: 35.35%

In [298]:
print("=" * 70)
print("              FEATURE 6 - TIME-OF-DAY PATTERNS")
print("=" * 70)

print("\nSpending by Time Period:")
print(period_spending)

print("\nBusiest Hour:")
print(
    f"{busiest_hour}:00 "
    f"₹{busiest_hour_amount:,.2f}"
)

print("\nTop Category by Time Period:")

for period in ["Morning", "Afternoon", "Evening", "Night"]:

    data = period_category[
        period_category["time_period"] == period
    ].sort_values("amount", ascending=False)

    if len(data) > 0:
        top_category = data.iloc[0]

        print(
            f"{period}: "
            f"{top_category['category']} "
            f"₹{top_category['amount']:,.2f}"
        )

print("\nSwiggy 9 PM–1 AM:")
print(f"{swiggy_percentage:.2f}%")

print("\nCafe 8 AM–11 AM:")
print(f"{cafe_percentage:.2f}%")

print("=" * 70)

======================================================================
              FEATURE 6 - TIME-OF-DAY PATTERNS
======================================================================

Spending by Time Period:
time_period
Morning      501130.0
Afternoon    452169.0
Evening      363884.0
Night        361718.0
Name: amount, dtype: float64

Busiest Hour:
10:00 ₹140,526.00

Top Category by Time Period:
Morning: E-commerce ₹157,003.00
Afternoon: E-commerce ₹180,106.00
Evening: E-commerce ₹134,508.00
Night: E-commerce ₹132,260.00

Swiggy 9 PM–1 AM:
21.81%

Cafe 8 AM–11 AM:
35.35%
======================================================================

## Feature 7 — Anomaly Detection.

In [299]:
# Feature 7 - Anomaly Detection

category_mean = (
    df.groupby("category")["amount"]
    .transform("mean")
)

print(category_mean.head())

0     3510.912791
1      229.896000
2    21412.433333
3    21412.433333
4      516.301587
Name: amount, dtype: float64

In [300]:
category_std = (
    df.groupby("category")["amount"]
    .transform("std")
)

print(category_std.head())

0     4522.129715
1      147.398938
2    32981.947367
3    32981.947367
4      205.472344
Name: amount, dtype: float64

In [301]:
df["z_score"] = (
    (df["amount"] - category_mean)
    / category_std
)

In [302]:
print(df[[
    "Description",
    "category",
    "amount",
    "z_score"
]].head(10))

                        Description           category   amount   z_score
0                AMAZON SELLER SVCS         E-commerce   2462.0 -0.231951
1                         BHIM-BMTC          Transport     50.0 -1.220470
2  NEFT-TECHCRUSH LABS-SALARY MAY24  Personal Transfer  84728.0  1.919704
3              UPI-AMAN-8934@OKAXIS  Personal Transfer   1828.0 -0.593793
4                      BHIM-BLINKIT     Quick Commerce    270.0 -1.198709
5                        BHIM ZEPTO     Quick Commerce    625.0  0.529017
6            UPI-UBER-2426@HDFCBANK          Transport    148.0 -0.555608
7                      BHIM-BLINKIT     Quick Commerce    482.0 -0.166940
8              POS SWIGGY BANGALORE      Food Delivery    537.0  0.637312
9             UPI-GROWWPAY@HDFCBANK        Investments   3956.0 -1.271042

In [303]:
df["is_anomaly"] = df["z_score"] > 2

In [304]:
print(
    "Number of anomalies:",
    df["is_anomaly"].sum()
)

Number of anomalies: 30

In [305]:
anomalies = (
    df[df["is_anomaly"]]
    .sort_values("z_score", ascending=False)
)

In [306]:
print("\nTop 5 Anomalies:")
print(
    anomalies[
        [
            "date",
            "vendor_clean",
            "category",
            "amount",
            "z_score"
        ]
    ]
    .head(5)
    .to_string(index=False)
)

Top 5 Anomalies:
      date vendor_clean    category  amount  z_score
2024-06-26       Amazon  E-commerce 22008.0 4.090349
2024-02-07       Amazon  E-commerce 21986.0 4.085484
2024-02-26  Restaurants Restaurants  8383.0 3.884639
2024-03-05       Amazon  E-commerce 19917.0 3.627956
2024-06-22  Restaurants Restaurants  7935.0 3.627582

In [307]:
print("=" * 70)
print("                 FEATURE 7 - ANOMALY DETECTION")
print("=" * 70)

print(f"\nTotal anomalies: {df['is_anomaly'].sum()}")

print("\nTop 5 Anomalies:")
print(
    anomalies[
        [
            "date",
            "vendor_clean",
            "category",
            "amount",
            "z_score"
        ]
    ]
    .head(5)
    .to_string(index=False)
)

print("=" * 70)

======================================================================
                 FEATURE 7 - ANOMALY DETECTION
======================================================================

Total anomalies: 30

Top 5 Anomalies:
      date vendor_clean    category  amount  z_score
2024-06-26       Amazon  E-commerce 22008.0 4.090349
2024-02-07       Amazon  E-commerce 21986.0 4.085484
2024-02-26  Restaurants Restaurants  8383.0 3.884639
2024-03-05       Amazon  E-commerce 19917.0 3.627956
2024-06-22  Restaurants Restaurants  7935.0 3.627582
======================================================================

## Feature 8 — Spending Archetype Detection.

In [308]:
# Feature 8 - Spending Archetype Detection

total_debits = df.loc[
    df["type_clean"] == "debit",
    "amount"
].sum()

print("Total debits:", total_debits)

Total debits: 1678901.0

In [309]:
print(df.columns.tolist())

['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode', 'Ref', 'date', 'amount', 'type_clean', 'vendor_clean', 'category', 'month', 'month_name', 'hour', 'time_period', 'z_score', 'is_anomaly']

In [310]:
category_spending = (
    df[df["type_clean"] == "debit"]
    .groupby("category")["amount"]
    .sum()
)

category_percentage = (
    category_spending / total_debits
) * 100

print("Category spending percentage:")
print(category_percentage.sort_values(ascending=False))

Category spending percentage:
category
E-commerce           35.968589
Investments          14.781098
Food Delivery         9.510209
Personal Transfer     7.897964
Restaurants           7.012742
Fuel                  5.319134
Quick Commerce        3.874797
Groceries             3.538446
Transport             3.423311
Cash Withdrawal       2.710106
Utilities             2.496514
Cafe                  1.872951
Subscriptions         1.100184
Entertainment         0.493954
Name: amount, dtype: float64

In [311]:
# Late-Night Snacker

food_delivery = df[
    (df["type_clean"] == "debit") &
    (df["category"] == "Food Delivery")
]

total_food_delivery_transactions = len(food_delivery)

late_night_food = food_delivery[
    (food_delivery["hour"] >= 21) |
    (food_delivery["hour"] <= 2)
]

late_night_percentage = (
    len(late_night_food) /
    total_food_delivery_transactions
) * 100

print("Total Food Delivery transactions:",
      total_food_delivery_transactions)

print("Late-night Food Delivery transactions:",
      len(late_night_food))

print(f"Late-night percentage: {late_night_percentage:.2f}%")

Total Food Delivery transactions: 364
Late-night Food Delivery transactions: 78
Late-night percentage: 21.43%

In [312]:
subscription_vendors = df[
    (df["type_clean"] == "debit") &
    (df["category"] == "Subscriptions")
]["vendor_clean"].dropna().unique()

print("Subscription vendors:")
print(subscription_vendors)

print("\nNumber of distinct subscription vendors:",
      len(subscription_vendors))

Subscription vendors:
['Netflix' 'Spotify' 'Disney Hotstar']

Number of distinct subscription vendors: 3

In [313]:
print("Savings rate:", savings_rate)

Savings rate: -229.34221831635196

In [314]:
print("=" * 75)
print("FEATURE 8 - SPENDING ARCHETYPE DETECTION")
print("=" * 75)

archetypes = {
    "THE FOODIE": (
        category_percentage.get("Food Delivery", 0)
        + category_percentage.get("Restaurants", 0)
        + category_percentage.get("Cafe", 0)
    ),

    "THE QUICK COMMERCE JUNKIE":
        category_percentage.get("Quick Commerce", 0),

    "THE SHOPAHOLIC":
        category_percentage.get("E-commerce", 0),

    "THE INVESTOR":
        category_percentage.get("Investments", 0),

    "THE LATE-NIGHT SNACKER":
        late_night_percentage,

    "THE CAB COMMUTER":
        category_percentage.get("Transport", 0),

    "THE SUBSCRIPTION LOVER":
        len(subscription_vendors),

    "THE YOLO SPENDER":
        savings_rate,

    "THE DISCIPLINED SAVER":
        savings_rate
}

# Apply the rules
results = {
    "THE FOODIE":
        archetypes["THE FOODIE"] > 25,

    "THE QUICK COMMERCE JUNKIE":
        archetypes["THE QUICK COMMERCE JUNKIE"] > 15,

    "THE SHOPAHOLIC":
        archetypes["THE SHOPAHOLIC"] > 15,

    "THE INVESTOR":
        archetypes["THE INVESTOR"] > 15,

    "THE LATE-NIGHT SNACKER":
        archetypes["THE LATE-NIGHT SNACKER"] > 50,

    "THE CAB COMMUTER":
        archetypes["THE CAB COMMUTER"] > 10,

    "THE SUBSCRIPTION LOVER":
        archetypes["THE SUBSCRIPTION LOVER"] >= 5,

    "THE YOLO SPENDER":
        archetypes["THE YOLO SPENDER"] < 10,

    "THE DISCIPLINED SAVER":
        archetypes["THE DISCIPLINED SAVER"] > 40
}

print("\nArchetype Results:")

for name, applies in results.items():

    metric = archetypes[name]

    if name == "THE SUBSCRIPTION LOVER":
        print(
            f"{name}: "
            f"{'YES' if applies else 'NO'} "
            f"({metric} distinct vendors)"
        )
    else:
        print(
            f"{name}: "
            f"{'YES' if applies else 'NO'} "
            f"({metric:.2f}%)"
        )

print("\n" + "=" * 75)
print("ARCHETYPES THAT APPLY TO RAHUL")
print("=" * 75)

matched = [
    name for name, applies in results.items()
    if applies
]

for name in matched:
    metric = archetypes[name]

    if name == "THE SUBSCRIPTION LOVER":
        print(f"{name} → {metric} distinct vendors")
    else:
        print(f"{name} → {metric:.2f}%")

print("=" * 75)

===========================================================================
FEATURE 8 - SPENDING ARCHETYPE DETECTION
===========================================================================

Archetype Results:
THE FOODIE: NO (18.40%)
THE QUICK COMMERCE JUNKIE: NO (3.87%)
THE SHOPAHOLIC: YES (35.97%)
THE INVESTOR: NO (14.78%)
THE LATE-NIGHT SNACKER: NO (21.43%)
THE CAB COMMUTER: NO (3.42%)
THE SUBSCRIPTION LOVER: NO (3 distinct vendors)
THE YOLO SPENDER: YES (-229.34%)
THE DISCIPLINED SAVER: NO (-229.34%)

===========================================================================
ARCHETYPES THAT APPLY TO RAHUL
===========================================================================
THE SHOPAHOLIC → 35.97%
THE YOLO SPENDER → -229.34%
===========================================================================

## final report

In [317]:
# ============================================================
#                 FINAL SPENDDNA REPORT
# ============================================================

print("=" * 70)
print("                 SpendDNA REPORT")
print("=" * 70)

# ------------------------------------------------------------
# 1. EXECUTIVE SUMMARY
# ------------------------------------------------------------

total_credits = df.loc[
    df["type_clean"] == "credit", "amount"
].sum()

total_debits = df.loc[
    df["type_clean"] == "debit", "amount"
].sum()

net_savings = total_credits - total_debits

savings_rate = (
    net_savings / total_credits * 100
    if total_credits != 0 else 0
)

transaction_count = len(df)

unique_vendors = df["vendor_clean"].nunique()

print("\nEXECUTIVE SUMMARY")
print("-" * 70)

print(f"Total credits       : Rs. {total_credits:,.2f}")
print(f"Total debits        : Rs. {total_debits:,.2f}")
print(f"Net savings         : Rs. {net_savings:,.2f}")
print(f"Savings rate        : {savings_rate:.2f}%")
print(f"Transactions         : {transaction_count}")
print(f"Unique vendors      : {unique_vendors}")


# ------------------------------------------------------------
# 2. TOP 5 CATEGORIES
# ------------------------------------------------------------

debit_df = df[df["type_clean"] == "debit"].copy()

category_spending = (
    debit_df
    .groupby("category")["amount"]
    .sum()
    .sort_values(ascending=False)
)

print("\nTOP 5 CATEGORIES")
print("-" * 70)

for category, amount in category_spending.head(5).items():

    percentage = amount / total_debits * 100

    print(
        f"{category:<20} "
        f"{percentage:>6.2f}%   "
        f"Rs. {amount:>10,.2f}"
    )


# ------------------------------------------------------------
# 3. TOP 5 VENDORS
# ------------------------------------------------------------

vendor_spending = (
    debit_df
    .groupby("vendor_clean")["amount"]
    .agg(["sum", "count"])
    .sort_values("sum", ascending=False)
)

print("\nTOP 5 VENDORS")
print("-" * 70)

for vendor, row in vendor_spending.head(5).iterrows():

    print(
        f"{vendor:<20} "
        f"Rs. {row['sum']:>10,.2f} "
        f"({int(row['count'])} orders)"
    )


# ------------------------------------------------------------
# 4. TIME-OF-DAY PATTERNS
# ------------------------------------------------------------

# Extract hour from Time column
df["hour"] = (
    df["Time"]
    .astype(str)
    .str[:2]
    .astype(int)
)

food_delivery = debit_df[
    debit_df["category"] == "Food Delivery"
]

food_delivery_hours = (
    food_delivery["Time"]
    .astype(str)
    .str[:2]
    .astype(int)
)

late_night_food = food_delivery[
    (food_delivery_hours >= 21) |
    (food_delivery_hours <= 2)
]

late_night_percentage = (
    len(late_night_food) / len(food_delivery) * 100
    if len(food_delivery) > 0 else 0
)

# Cafe peak hour
cafe_df = debit_df[
    debit_df["category"] == "Cafe"
]

if len(cafe_df) > 0:

    cafe_hours = (
        cafe_df["Time"]
        .astype(str)
        .str[:2]
        .astype(int)
    )

    cafe_peak_hour = cafe_hours.value_counts().idxmax()

else:
    cafe_peak_hour = None


# Quick Commerce dominant time period
quick_df = debit_df[
    debit_df["category"] == "Quick Commerce"
].copy()


def get_time_period(hour):

    if 5 <= hour < 12:
        return "Morning"

    elif 12 <= hour < 17:
        return "Afternoon"

    elif 17 <= hour < 21:
        return "Evening"

    else:
        return "Night"


if len(quick_df) > 0:

    quick_hours = (
        quick_df["Time"]
        .astype(str)
        .str[:2]
        .astype(int)
    )

    quick_periods = quick_hours.apply(get_time_period)

    quick_peak_period = quick_periods.value_counts().idxmax()

else:
    quick_peak_period = "No data"


print("\nTIME-OF-DAY PATTERNS")
print("-" * 70)

print(
    f"Food Delivery late-night : "
    f"{late_night_percentage:.2f}% "
    f"(21:00 - 02:00)"
)

if cafe_peak_hour is not None:

    print(
        f"Cafe peak hour          : "
        f"{cafe_peak_hour:02d}:00"
    )

print(
    f"Quick Commerce pattern   : "
    f"{quick_peak_period}"
)


# ------------------------------------------------------------
# 5. MONTHLY TREND - FOOD DELIVERY
# ------------------------------------------------------------

df["month_num"] = df["date"].dt.month

month_names = {
    1: "Jan",
    2: "Feb",
    3: "Mar",
    4: "Apr",
    5: "May",
    6: "Jun"
}

food_monthly = (
    df[
        (df["type_clean"] == "debit") &
        (df["category"] == "Food Delivery")
    ]
    .groupby("month_num")["amount"]
    .sum()
)

print("\nMONTHLY TREND - FOOD DELIVERY")
print("-" * 70)

for month_num in range(1, 7):

    amount = food_monthly.get(month_num, 0)

    print(
        f"{month_names[month_num]} "
        f"Rs. {amount:,.2f}"
    )

# ------------------------------------------------------------
# 6. ANOMALY DETECTION
# ------------------------------------------------------------

# Category mean and standard deviation
category_mean = (
    debit_df
    .groupby("category")["amount"]
    .transform("mean")
)

category_std = (
    debit_df
    .groupby("category")["amount"]
    .transform("std")
)

debit_df["z_score"] = (
    (debit_df["amount"] - category_mean)
    / category_std
)

anomalies = debit_df[
    debit_df["z_score"] > 2
].sort_values(
    "z_score",
    ascending=False
)

print("\nTOP 5 ANOMALIES")
print("-" * 70)

for _, row in anomalies.head(5).iterrows():

    date_value = row["date"]

    if pd.notna(date_value):
        date_text = date_value.strftime("%d %b")
    else:
        date_text = "Unknown"

    print(
        f"{date_text:<10} "
        f"{row['vendor_clean']:<18} "
        f"Rs. {row['amount']:>9,.2f} "
        f"(z={row['z_score']:.2f})"
    )

print(f"\nTotal anomalies: {len(anomalies)}")


# ------------------------------------------------------------
# 7. SPENDING ARCHETYPES
# ------------------------------------------------------------

category_percentage = (
    category_spending / total_debits * 100
)

foodie_percentage = (
    category_percentage.get("Food Delivery", 0)
    + category_percentage.get("Restaurants", 0)
    + category_percentage.get("Cafe", 0)
)

quick_percentage = (
    category_percentage.get("Quick Commerce", 0)
)

ecommerce_percentage = (
    category_percentage.get("E-commerce", 0)
)

investment_percentage = (
    category_percentage.get("Investments", 0)
)

transport_percentage = (
    category_percentage.get("Transport", 0)
)

subscription_vendors = debit_df[
    debit_df["category"] == "Subscriptions"
]["vendor_clean"].dropna().unique()

subscription_count = len(subscription_vendors)


archetypes = []

if foodie_percentage > 25:
    archetypes.append(
        ("THE FOODIE", f"{foodie_percentage:.2f}% on food")
    )

if quick_percentage > 15:
    archetypes.append(
        (
            "THE QUICK COMMERCE JUNKIE",
            f"{quick_percentage:.2f}% on Quick Commerce"
        )
    )

if ecommerce_percentage > 15:
    archetypes.append(
        (
            "THE SHOPAHOLIC",
            f"{ecommerce_percentage:.2f}% on E-commerce"
        )
    )

if investment_percentage > 15:
    archetypes.append(
        (
            "THE INVESTOR",
            f"{investment_percentage:.2f}% on Investments"
        )
    )

if late_night_percentage > 50:
    archetypes.append(
        (
            "THE LATE-NIGHT SNACKER",
            f"{late_night_percentage:.2f}% of Food Delivery transactions late-night"
        )
    )

if transport_percentage > 10:
    archetypes.append(
        (
            "THE CAB COMMUTER",
            f"{transport_percentage:.2f}% on Transport"
        )
    )

if subscription_count >= 5:
    archetypes.append(
        (
            "THE SUBSCRIPTION LOVER",
            f"{subscription_count} subscription vendors"
        )
    )

if savings_rate < 10:
    archetypes.append(
        (
            "THE YOLO SPENDER",
            f"savings rate {savings_rate:.2f}%"
        )
    )

if savings_rate > 40:
    archetypes.append(
        (
            "THE DISCIPLINED SAVER",
            f"savings rate {savings_rate:.2f}%"
        )
    )


print("\nRAHUL'S SPENDING ARCHETYPES")
print("-" * 70)

for name, metric in archetypes:

    print(
        f"-> {name:<30} ({metric})"
    )


# ------------------------------------------------------------
# 8. KEY INSIGHTS
# ------------------------------------------------------------

top_category = category_spending.index[0]
top_category_amount = category_spending.iloc[0]

top_vendor = vendor_spending.index[0]
top_vendor_amount = vendor_spending.iloc[0]["sum"]

print("\nKEY INSIGHTS")
print("-" * 70)

print(
    f"1. Rahul's spending is highest in "
    f"{top_category}, with Rs. {top_category_amount:,.2f} spent."
)

print(
    f"2. {top_vendor} is the highest-spend vendor, "
    f"with Rs. {top_vendor_amount:,.2f} spent."
)

print(
    f"3. Rahul's savings rate is {savings_rate:.2f}%, "
    f"indicating an overspending pattern."
)

print(
    f"4. {late_night_percentage:.2f}% of Food Delivery "
    f"transactions occur between 21:00 and 02:00."
)

print(
    f"5. The analysis identified {len(anomalies)} "
    f"anomalous transactions."
)

print("\n" + "=" * 70)
print("                    END OF REPORT")
print("=" * 70)

======================================================================
                 SpendDNA REPORT
======================================================================

EXECUTIVE SUMMARY
----------------------------------------------------------------------
Total credits       : Rs. 509,774.00
Total debits        : Rs. 1,678,901.00
Net savings         : Rs. -1,169,127.00
Savings rate        : -229.34%
Transactions         : 1310
Unique vendors      : 37

TOP 5 CATEGORIES
----------------------------------------------------------------------
E-commerce            35.97%   Rs. 603,877.00
Investments           14.78%   Rs. 248,160.00
Food Delivery          9.51%   Rs. 159,667.00
Personal Transfer      7.90%   Rs. 132,599.00
Restaurants            7.01%   Rs. 117,737.00

TOP 5 VENDORS
----------------------------------------------------------------------
Amazon               Rs. 328,530.00 (86 orders)
Zerodha              Rs. 210,000.00 (14 orders)
Flipkart             Rs. 177,510.00 (47 orders)
Personal Transfer    Rs. 108,000.00 (6 orders)
Swiggy               Rs. 104,351.00 (243 orders)

TIME-OF-DAY PATTERNS
----------------------------------------------------------------------
Food Delivery late-night : 21.43% (21:00 - 02:00)
Cafe peak hour          : 10:00
Quick Commerce pattern   : Evening

MONTHLY TREND - FOOD DELIVERY
----------------------------------------------------------------------
Jan Rs. 23,692.00
Feb Rs. 26,458.00
Mar Rs. 25,918.00
Apr Rs. 30,092.00
May Rs. 26,598.00
Jun Rs. 26,909.00

TOP 5 ANOMALIES
----------------------------------------------------------------------
26 Jun     Amazon             Rs. 22,008.00 (z=4.09)
07 Feb     Amazon             Rs. 21,986.00 (z=4.09)
26 Feb     Restaurants        Rs.  8,383.00 (z=3.88)
05 Mar     Amazon             Rs. 19,917.00 (z=3.63)
22 Jun     Restaurants        Rs.  7,935.00 (z=3.63)

Total anomalies: 30

RAHUL'S SPENDING ARCHETYPES
----------------------------------------------------------------------
-> THE SHOPAHOLIC                 (35.97% on E-commerce)
-> THE YOLO SPENDER               (savings rate -229.34%)

KEY INSIGHTS
----------------------------------------------------------------------
1. Rahul's spending is highest in E-commerce, with Rs. 603,877.00 spent.
2. Amazon is the highest-spend vendor, with Rs. 328,530.00 spent.
3. Rahul's savings rate is -229.34%, indicating an overspending pattern.
4. 21.43% of Food Delivery transactions occur between 21:00 and 02:00.
5. The analysis identified 30 anomalous transactions.

======================================================================
                    END OF REPORT
======================================================================